import type { Metadata } from "next";
import { archivoblack, bali, dmsans, monasans } from "@/lib/font";
import "@/styles/globals.css";
import "@/styles/shadcn.css";
import "@/styles/basic.css";
import QueryProvider from "@/utils/queryProvider";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${monasans.variable} ${dmsans.variable} ${archivoblack.variable} ${bali.variable} bg-[#081028] antialiased`}
      >
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="max-w-[1440px] mx-auto">
              <div className="px-c-11 py-c-9">{children}</div>
            </main>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
