import type { Metadata } from "next";
import { archivoblack, bali, dmsans, monasans, worksasns } from "@/lib/font";
import QueryProvider from "@/utils/queryProvider";
import { ThemeProvider } from "@/components/ui/layout/theme-provider";
import "../styles/global.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/shadcn/sidebar";
import { AppSidebar } from "@/components/ui/layout/sidebar/sidebar";
import { SiteHeader } from "@/components/ui/layout/header";
import { ReactNode } from "react";
import { SiteMain } from "@/components/ui/layout/main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${monasans.variable} ${dmsans.variable} ${archivoblack.variable} ${bali.variable} ${worksasns.variable} antialiased`}
      >
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider className="flex justify-center">
              <AppSidebar />
              <SidebarInset>
                <SiteHeader />
                <SiteMain>{children}</SiteMain>
              </SidebarInset>
            </SidebarProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
